### ISSUE TITLE
Fortran 2008 features: submodule-related keywords

### ISSUE THREAD

**Issue by szaghi** [lervag/dotvim#1]
Dear @lervag ,

I am sorry to bother you. You are using a very recent Fortran vim syntax (more than mine that is dated 2012), so I hope you can help me.

I am searching for a Fortran vim syntax file that supports `submodule` related keywords. In particular, let us consider the following snippet:

```fortran
submodule (foo) bar
contains
  module subroutine foo_bar
  ...
  end subroutine foo_bar
endsubmodule bar
``` 

I want:
+ highlight `submodule` and `endsubmodule`;
+ enable folding of `module subroutine/end subroutine` and `module function/end function`.

Can you help? Had you patched your Fortran syntax file or can you point me to whom did it?

Thank you very much in advance.

My best regards.

**Comment by szaghi** [comment]
@lervag 

I am very sorry, I have just checked at the Ajit homepage and I found the updated fortran.vim (it seems that in 2016 a new version has been released).

Sorry for the bothering.

My best regards.

**Comment by lervag** [comment]
Hi. Yes, I've updated the syntax file in order to add support for continued conditional statements, i.e. long if statements. You can see what I changed if you search in my version for "Note:" (I've commented where I've changed/added code). I see my version is slightly old, but it seems there is very little that has been updated since 2015. In any case, thanks for making me aware that I should update my fortran syntax file :)
