### ISSUE TITLE
wiki usage

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/dotvim#2]
Hey @lervag,

Just had a look at your vim config, and it's very interesting. A lot of plugins that I didn't know about (like context.vim), and a lot that we have in common (like coc-nvim).

I see that you have your own wiki plugin, and was wondering how is that working for you. **What is your workflow with it?**

I personally have [jrnl](https://jrnl.sh/) for journaling (became more like a sport tracker recently), [taskwarrior](https://taskwarrior.org/) for tasks (not using at all recently, doing everything on github..) and apy for flashcards (thank you so much for that). Countless other tools that I do not manage properly (google docs/spreadsheets, milanote, slack, etc).
While most of the notes that I find worthwhile writing down go directly in Anki, I'm not satisfied with my knowledge management system.

I want to find some time to study more about stuff like BASB, PARA, CFAR, Byron Katie's The work, Zettelkasten & co, but I'm afraid that it's quite low in my icebox of things to do. In that case, mimicking fellow vim/python/anki/tmux/zsh/etc user sounds like a good strategy ^^'

**Comment by lervag** [comment]
> Just had a look at your vim config, and it's very interesting. A lot of plugins that I didn't know about (like context.vim), and a lot that we have in common (like coc-nvim).

Thanks. I'm still always changing it, but it is working well for me now.

> I see that you have your own wiki plugin, and was wondering how is that working for you. **What is your workflow with it?**

It's one of my favourite things, actually. My workflow is something like this:

* I have a mapping in my DE (fluxbox) to quickly open my wiki index (mapped to `<m-n>` (Alt+n). I've further mapped `<space>ow` to use FZF to search my wiki pages/files. This is a crucial part of my workflow, because it allows me to access my notes VERY quickly. If I have a thought, it can be put into my notes (either in the index or at a dedicated position within at max a few seconds.

* Within the wiki, I have a semi pragmatic approach where I tend to structure my "knowledge base" in a flat hierarchy (most of my pages are in the same root directory). I have a lot of links between relevant parts, and the wiki plugin makes it very easy both to traverse links and to create/modify links (hotkeys and completion). I can also display "graphs" between the pages.

* I keep a daily journal (for work), which is also in my wiki. This is in a separate folder. This keeps my number of hours on different projects, as well as key points about what I've done for each of my projects/activities. I make summaries at the end of a week and end of a month. Since things are structured I have some commands to help make these summaries much faster.

That's mostly it, really. In my personal opinion, the most important thing about note keeping is to make your notes _very accessible_ and _structured_. With structured, I mean to make it easy to look up something and find related information. E.g., when I look at my `tmux` page, I get links to related things like `terminfo` and `screen`, and also `tmate`. The latter was something I discovered once and found useful a couple of times. In the page about `tmate`, I've also linked to `teleconsole`, which is a similar tool. My pages for these two things are short and mostly contains links to relevant web pages. Since I've tried out `tmate`, I've also copied down my API key and how I've configured it to work. Thus, if I were to use it again in a year, I would be able to pick things up much more quickly.

Although I sometimes do take note of things like an API key in my wiki, I use `password-store` to store my sensitive information (e.g. passwords and such). I can then just take note for some service in my wiki to look up my password.

My workflow is **not** perfect. For instance, I do spend manual effort on keeping my list of TODO's both for work and personal projects. This could be automated and improved, perhaps with e.g. taskwarrior. Still, I don't find this to be a very important "defect", and I'm generally very happy with my workflow.

> I personally have [jrnl](https://jrnl.sh/) for journaling (became more like a sport tracker recently), [taskwarrior](https://taskwarrior.org/) for tasks (not using at all recently, doing everything on github..) and apy for flashcards (thank you so much for that). Countless other tools that I do not manage properly (google docs/spreadsheets, milanote, slack, etc).
> While most of the notes that I find worthwhile writing down go directly in Anki, I'm not satisfied with my knowledge management system.

Then I would strongly recommend to test my workflow. You could try my plugin, but it should also work well with Vimwiki.

I do still actively maintain and develop wiki.vim, so if I have users invested in it I will be glad to cooperate to improve things and add useful new features.

> I want to find some time to study more about stuff like BASB, PARA, CFAR, Byron Katie's The work, Zettelkasten & co, but I'm afraid that it's quite low in my icebox of things to do. In that case, mimicking fellow vim/python/anki/tmux/zsh/etc user sounds like a good strategy ^^'

Definitely. As stated, I don't know if my workflow is superior to others, but it does work very well for me. I think my observations mentioned about accessibility and keeping things somewhat organized are crucial and you will also find them mentioned in other apps/tools. OneNote on windows have shortcuts, for instance, to quickly open whenever you need it. It does give me peace of mind, though, to know that I control my data, both the content and the workflow.

**Comment by AdrienLemaire** [comment]
I was not expecting such a thoughtful reply, thanks for taking that time.

I still have some hard questions ^^. 

For example, how can I jot down notes when running on my phone and review them in wiki.vim ?

Quick brainstorming gives me:
1. Google keep speech-to-text (ah google keep, another tool where I have a lot of notes...)
2. unofficial [gkeepapi](https://github.com/kiwiz/gkeepapi) library to sync notes with wiki.vim (but I'd want some `keep` tag to control what data I share with google keep.

The opposite would be very valuable as well.. Being able to search my knowledge from my phone on the go...

Another one would be getting anki cards details when searching a keyword in wiki.vim. This one's easy: sync with apy.

I'm assuming that a good modern knowledge management system is a plugin-based platform that's accessible from anywhere. But now, I guess this is going against your "do one thing and do it well" philosophy ?

Would love to hear your opinion on this. 
Anyways, the issue's topic has been answered, so closing it (and sorry for asking it in your dotvim repo, I hadn't realized that you had the wiki.vim repo at that time ^^'

**Comment by lervag** [comment]
> I was not expecting such a thoughtful reply, thanks for taking that time.

It's always fun to share, and related discussions can be useful also for me to learn something/be inspired! :)

> For example, how can I jot down notes when running on my phone and review them in wiki.vim ?

Good question! Currently, I store my wiki via on Dropbox and access it with Vimdroid through Dropbox on my phone. This works quite well, but I have not taken the time to properly setup Vimdroid on my phone. It therefore does not feel quite optimal.

My current goal is to put my wiki on [Syncthing](https://syncthing.net/) and test the app Markor for reading and editing my notes from my phone.  However, I have some issues with Syncthing at work due to our firewall, so I have not been able to test this yet. I do believe this might feel better, though, when I get it to work.

I probably spend 99.9% of my productive time on my computer, though, so I never really found this to be very limiting.

> The opposite would be very valuable as well.. Being able to search my knowledge from my phone on the go...

This does work quite well with Dropbox, actually.

> Another one would be getting anki cards details when searching a keyword in wiki.vim. This one's easy: sync with apy.

Yes, perhaps. I've never really aimed for a sync between my Anki notes and my wiki notes, except for in the sense of keeping track of things I want to push into Anki.

I'll admit this means I sometimes to make redundant notes. That is, I may write a wiki note about something and simultaneously write similar Anki flashcards. I don't consider this a problem, though.

> I'm assuming that a good modern knowledge management system is a plugin-based platform that's accessible from anywhere. But now, I guess this is going against your "do one thing and do it well" philosophy ?

I think what is considered "a good, modern" knowledge management system depends on the user. Modern is not important for me, but "good" implies that the system is accessible, available, searchable, and that it works well with different tools. Since I've decided to "run my own" with vim and wiki.vim, I have ended up with a knowledge management system where the data is 100% controlled by me. Files are pure text and is easily and very efficiently searched with tools like `fd` and `rg`. Vim allows me to add the features I want, the most important one being how to handle links between notes and links to external content.

As an example, I've recently started to use Zotero to handle my literature database (I work as a researcher). I've found this works very well, and it also works well with wiki.vim since I've implemented support for Zotero links.

I hope this is useful. Feel free to open issues on wiki.vim and raise questions or ideas for improving it. It could also be relevant to add a Wiki on that repo with ideas on how to work with a Vim based wiki on your phone. As you might understand from the above, I'm not fully settled on this point myself. Ever evolving. :)
